Mobirise icons added
front-end-by-rimantas/19-grupe-portfolio-elvish pull request #37
Opened 2020-12-10 22:24 UTC by Gabrieleba

2020-12-10 23:49 UTC, sezaite requested changes
neimportuotas linkas į ikonas

2020-12-11 13:12 UTC, sezaite reviewed
headery ikona palikta

2020-12-11 13:18 UTC, sezaite approved these changes
LVeryGTM

2020-12-11 13:24 UTC, Urbbiz approved these changes
LGTM

2020-12-11 13:24 UTC, merged