Footer
front-end-by-rimantas/19-grupe-portfolio-elvish pull request #79
Opened 2020-12-15 17:01 UTC by ESinkev

2020-12-15 17:33 UTC, sezaite requested changes
reiktu pakeisti font

2020-12-16 06:51 UTC, Urbbiz approved these changes

2020-12-16 08:22 UTC, Tomas3000 approved these changes

2020-12-16 11:38 UTC, ESinkev commented
> reiktu pakeisti font

pakeistas font.

2020-12-16 11:55 UTC, Gabrieleba approved these changes

2020-12-16 12:18 UTC, sezaite approved these changes

2020-12-16 12:18 UTC, merged